### ISSUE TITLE
Inconsistent on first load

### ISSUE THREAD

**Issue by ronluna** [aksyonov/lovelace-area-background#3] opened 2023-04-06 20:52 UTC
Wondering if you are getting similar results between dashboards that are using the lovelace-area-background and dashboards that are not...but when jumping between them the background image won't load unless the user clicks somewhere around the background at least once or by clicking on another view that has an area background specified.

any clues?

**Comment by aksyonov** [comment] 2023-04-07 08:10
it depends on the client - it seems to work fine on Windows and mac (in a browser and official app), but I did notice this behavior in Android and iOS apps. Will try to fix it when I'll have time.
Also, I'm open to pull requests if someone finds a way to fix this before I do.

**Comment by aksyonov** [comment] 2023-04-07 18:39
@ronluna could you try and see if the issue is fixed in [v1.0.4](https://github.com/aksyonov/lovelace-area-background/releases/tag/v1.0.4)?

**Comment by ronluna** [comment] 2023-04-08 21:39
Seems to be working great now... Thanks!

**Closed** 2023-04-09 07:53 UTC
